### ISSUE TITLE
Doesn't update on changing properties

### ISSUE THREAD

**Issue by sdpjswl** [shashankpali/EZYGradientView#1]
I added a gradient view on storyboard and made an outlet. I didn't use IBInspectable to customize it. I did it in `viewDidLoad` and it worked. Then I tried changing the `firstColor` property on a button tap and it didn't work.

**Comment by shashankpali** [comment]
Thanks Sudeep, I have solved the issue. Download the new version or update with pod to get the changes.

**Comment by sdpjswl** [comment]
Great, thanks.
