### ISSUE TITLE
Exposing gradientLayer property

### ISSUE THREAD

**Issue by vburojevic** [shashankpali/EZYGradientView#2]
Is it possible to expose gradientLayer property so we can customize it?
For example, I need to add a corner radius on EZYGradientView, but I need to set it on gradientLayer which is not exposed.

**Comment by shashankpali** [comment]
Hi Vedran,
Download the new version of EZYGradientView. It allow you to access the gradientLayer and blurLayer.

**Comment by vburojevic** [comment]
Awesome, thanks!

**Comment by shashankpali** [comment]
Most welcome...!
