### ISSUE TITLE
swift 3 support

### ISSUE THREAD

**Issue by antonioreyna** [shashankpali/EZYGradientView#3]
Hello are you planning on adding the swift 3 support? thanks!

**Comment by devJoshLopez** [comment]
Looking for the same. Much love

**Comment by SirVeryBritish** [comment]
+1

**Comment by guidev** [comment]
+1

**Comment by shashankpali** [comment]
Hi guys. Due to my busy schedule, I haven't been able to answer you. I am working on Swift 3 support. Will let you know as soon as I'm done with it. Thank you for your support.

**Comment by hunasdf** [comment]
+1

**Comment by rsomlette** [comment]
Took 5min to get it working. As you're blocking push Request. I forked your repo.
https://github.com/Niphery/EZYGradientView
use: pod 'EZYGradientView', :git => 'https://github.com/Niphery/EZYGradientView'
until @shashankpali decide to update/push it himself

**Comment by shashankpali** [comment]
Thank Niphery for your contribution.
